### PR TITLE
Reset authorship

### PR DESCRIPTION
**Pull request by ghost**
🥲

### CODE REVIEW

**Comment by Kinnara-icz** [comment]
Commit is pretty much like I just fix it maybe he doesn't care tho

**Comment by Kinnara-icz** [comment]
okay remove now, he corrected it. I contribute in my free time hahaa:skull:

**Comment by Asyanx** [comment]
done

**Comment by Asyanx** [comment]
✨ thank you :)

**Comment by Kinnara-icz** [comment]
nothing sir

**Comment by ghost** [comment]
okay sir, wait I'm resetting pr xd

**Pull request closed without merging**
